# Generated by Django 4.1.7 on 2023-03-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotesIndexPage',
            new_name='NoteIndexPage',
        ),
    ]
