# Generated by Django 4.1.7 on 2023-03-15 07:51

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='notes.notecategory'),
        ),
    ]
